### ISSUE TITLE
Creating channels should be true by default

### ISSUE THREAD

**Issue by shmulvad** [richfromm/slack2discord#23]
First of all, thank you very much for this project. I just used it to migrate a Slack workspace yesterday and it would have been a real pain, if not outright impossible, if I didn't have this. While migrating, I ran into a few issues from which I have a few requests. To be able to discuss different issues separately, I've opened a few issues. I can help to create a PR with some of the changes if you agree with them.

## The issue

I moved a Slack workspace to a completely fresh Discord server and imagine most people using this program would do the same. The first time I ran the program, I ran into a problem when the script tried to post messages because I didn't supply the `--create` parameter. I think this parameter should be true by default or at the very least also documented more clearly on this repository's README.

**Comment by richfromm** [comment]
Apologies for taking so long to respond to this. I didn't see any of these open issues until today. See https://github.com/richfromm/slack2discord/issues/22#issuecomment-1420214552

I'm a little torn about this. I think my thought process at the time was that I was reluctant to muck with someone's Discord server except in ways that they clearly anticipated. And that therefore I wanted to make channel creation an explicit request.

But maybe that's just being way overly cautious, and the common case is to create the channels, and therefore that should be the default, like you're suggesting.

Does anyone else have an opinion on this? If there's a consensus to change the default behavior, I'm fine with it. I'll try mentioning the small collection of people who have had something to say so far: @akvashi24 @waocats @ajroberts0417

**Comment by waocats** [comment]
Makes sense to me. I can't think of many scenarios where the destination channels don't already exist and you wouldn't want to create a channel to house those messages.

Here's what I am concerned about w/ the current implementation (maybe we make another issue for this, depending on your thoughts):
What if a channel does already exist, and then the user unknowingly adds (potentially) hundreds/thousands of Slack messages and buries the existing content? I would find that a worthy concern to exercise caution over, because that would cause more damage than just deleting a channel (which `--create` was trying to prevent)

**Comment by richfromm** [comment]
That's also a good point. My first reaction was that there could be a 3 way option, like `--allow-create`, `--no-create`, and something like `--force-create` to **require** that the channels not yet exist in Discord. But that might be problematic -- presumably `#general` in the common case is going to exist in both? (Not sure if that's an actual requirement.) I suppose you could special case `#general`, but that might be kind of confusing.

I'm wondering if you could also somehow bring in the state provided using `--channel-file` to help, but again I worry about making this configuration too complicated, and wanting things to be closer to just working in the common case without too many options.

Here's a different approach... There are two possible options.
* The default is that it goes through the list of channels (assuming they pass validation, see https://github.com/richfromm/slack2discord/issues/24), determines which (if any) existing channels it will post to, which (if any) channels do not exist and need to be created, then presents those lists to the user and prompts for agreement. If yes, then go ahead and do the migration. If no, then quit.
* The other (non-default) option would effectively be answering yes at the prompt. So we'd still log what was being done, but assume the user was okay with that.
* There would no longer be any option that would automatically fail. Which in theory might have a minor downside if you were trying to call this from some automated script, but I suspect that that may not describe any real world use case. 

Tentative naming suggestion, no option for the default scenario that prompts, and an optional option `--channel-noprompt` to not prompt the user and just go ahead and do whatever is needed.

Thoughts?

**Comment by richfromm** [comment]
If we do elect to prompt the user, should that just be done with raw print output, and bypass the use of logging, to make it stand out more and/or be easier to read?

**Comment by richfromm** [comment]
Maybe I'm overthinking options too much, and the one and only one behavior should be to prompt the user with a list of channels separated by existing channels and those that will be created, then prompt the user to confirm.

This removes the ability to easily run this in a 100% automatic way, but maybe that's okay? 

The info being prompted could even include whether the new channels are in a category or not, see https://github.com/richfromm/slack2discord/issues/32

**Comment by waocats** [comment]
I suppose there would be nothing wrong with having those options, but have prompting as default behavior. Personally, because our Slack group was so large and had years and years of messages, I would like to set all of the options and leave it unattended--though since this is right at invocation, I doubt it would really be _that_ much of an issue.

I guess that means that we just stick with prompting?

**Comment by richfromm** [comment]
Yeah, the goal would be all prompts would be at the beginning before it started actually doing the migration.

But as long as any prompt has some (probably default) "yes" answer of just agreeing with what the script wants to do, it would also be trivial to add a `--yes` option that would automate that.

**Comment by richfromm** [comment]
See my current plan [here](https://github.com/richfromm/slack2discord/issues/32#issuecomment-1425021595)

**Comment by richfromm** [comment]
Somewhat change of plan. I still like the idea of querying Discord state early, and (by default) prompting the user for confirmation regarding the category/channel situation, as outlined above. And I will try to get to it in the not too distant future.

But, for reasons discussed earlier, it's non-trivial to implement, given the async nature of the Discord API.

So for the short term resolution of this issue, I think it's fine to just switch the polarity of this behavior, which is what was originally suggested. The default will be to create channels, and for now the option will switch to `--no-create`. (I suspect this option may disappear if/when the long term plan is implemented.)

**Comment by richfromm** [comment]
re: @waocats 
> I can't think of many scenarios where the destination channels don't already exist and you wouldn't want to create a channel to house those messages.

I can think of one, you're using the `--channel-file` option and you have a typo.

But that's obviously not the common case, I agree that channel creation should be the default.
