### ISSUE TITLE
Allow reusing already downloaded images

### ISSUE THREAD

**Issue by shmulvad** [richfromm/slack2discord#26]
The bot spends a very long time downloading images because it is done sequentially and on every run. As you note, this could be sped up significantly by downloading them in parallel.

Another thing that also could be done though is to reuse downloaded images if the program has already been run. I tried to manually set the download directory, but all it accomplished was that it still downloaded images, just overwriting the previously downloaded images with exact copies. I think if the image is already there, it should be reused - especially if the user explicitly provides the download directory flag.

Finally, adding something like [`tqdm`](https://tqdm.github.io) during the image downloading would make the script more user friendly.

**Comment by richfromm** [comment]
Apologies for taking so long to respond to this. I didn't see any of these open issues until today. See https://github.com/richfromm/slack2discord/issues/22#issuecomment-1420214552

IIRC, one of my concerns about overwriting existing files was how to deal with the possibility that the file changed on the Slack side. Is this even possible? Like can a user edit an attachment to update a file that was uploaded to Slack? TBH, I'm not sure.

Maybe I'm being too paranoid? I suppose if the default behavior is to create a new (timestamp derived name) downloads directory, and you have to explicitly indicate that you want to reuse a directory, maybe that is a bit of excessive caution.

I could also look into how feasible it is to only download if the file size does not match, as suggested at https://github.com/richfromm/slack2discord/blob/2617f7e5b5bb85d14a24a4b4e93de4b30f5df73a/slack2discord/downloader.py#L99
